[env:ttgo-t-display]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DCGRAM_OFFSET=1
    -DTFT_WIDTH=135
    -DTFT_HEIGHT=240
    -DTFT_MISO=-1
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=16
    -DTFT_RST=23
    -DTFT_BL=4
    -DTFT_BACKLIGHT_ON=1
    -DLOAD_GLCD=1
    -DSPI_FREQUENCY=40000000
